# ДЗ №2

## 1 – Перемножение матриц

In [1]:
import numpy as np

In [2]:
def no_numpy_mult(first, second):
    
    length = len(first) 
    result = [[0 for i in range(length)] for i in range(length)]
        
    for i in range(length):
        for j in range(length):
            for k in range(length):
                result[i][j] += first[i][k] * second[k][j]

    return result

no_numpy_mult([[1,2,3],[3,2,1],[1,1,1]],[[1,2,3],[3,2,1],[1,1,1]])

[[10, 9, 8], [10, 11, 12], [5, 5, 5]]

In [3]:
def numpy_mult(first, second):

    result = first @ second
    
    return result

numpy_mult(np.array([[1,2,3],[3,2,1],[1,1,1]]),np.array([[1,2,3],[3,2,1],[1,1,1]]))

array([[10,  9,  8],
       [10, 11, 12],
       [ 5,  5,  5]])

## 2 – Скалярное произведение

In [4]:
import numpy as np

In [5]:
def no_numpy_scalar(v1, v2):
    
    result = sum(v1[i] * v2[i] for i in range(3))
    
    return result

no_numpy_scalar([1,2,3],[1,2,3])

14

In [6]:
def numpy_scalar (v1, v2):

    result = v1 @ v2
    
    return result

numpy_scalar(np.array([1,2,3]),np.array([1,2,3]))

14

## 3 – Сумма четных элементов на главной диагонали 

In [7]:
import numpy as np

In [8]:
def diag_2k(a):
    
    diag = np.diagonal(a)
    result = (np.sum(diag[diag % 2 == 0]))
    
    return result

diag_2k(np.array([[1,2,2],[4,10,1],[1,10,1]]))

10

## 4 –  Массив из построенных строчек

In [9]:
import numpy as np

In [10]:
def cumsum(A):
        
    result = np.array([np.hstack((A[i].cumsum())) for i in range(len(A))])
    result.shape = (len(A), len(A[0]))
    
    return result

cumsum(np.array([[1,2,2,32,2],[4,10,1,1,1],[1,10,1,4,5],[1,10,1,4,5]]))

array([[ 1,  3,  5, 37, 39],
       [ 4, 14, 15, 16, 17],
       [ 1, 11, 12, 16, 21],
       [ 1, 11, 12, 16, 21]])

## 5 – Склеивание

In [11]:
import numpy as np

In [12]:
def transform(X, a=1):
    
    result = np.copy(X) # важно!
    
    result[:,1::2] = a
    result[:,0::2] **= 3
                
    result = np.flip(result, 1)
    result = np.concatenate([X, result], axis = 1)
            
    return result

transform(np.array([[1,2,3,4,5],[4,10,1,1,1],[1,10,1,4,100]]))

array([[      1,       2,       3,       4,       5,     125,       1,
             27,       1,       1],
       [      4,      10,       1,       1,       1,       1,       1,
              1,       1,      64],
       [      1,      10,       1,       4,     100, 1000000,       1,
              1,       1,       1]])

## 6 – Run-length encoding

In [13]:
import numpy as np

In [14]:
def encode(a):
    
    is_new_in_row = np.array(a[1:] != a[:-1])
    position = np.append(np.where(is_new_in_row), len(a) - 1)
    lengths = np.diff(np.append(-1, position))
    
    return (a[position], lengths)

encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]))